import {writeFileSync,mkdirSync} from 'node:fs';
mkdirSync('dist',{recursive:true});
const pages={article:{label:'기사',n:'01',heading:'Words that<br>open <em>worlds.</em>',subtitle:'질문에서 시작해, 한 편의 이야기로.',desc:'AI와 함께 세상을 읽고, 나만의 시선으로 다시 쓰는 기사 아카이브.'},image:{label:'이미지',n:'02',heading:'Imagination,<br>made <em>visible.</em>',subtitle:'상상이 장면이 되는 순간.',desc:'단어와 빛, 질감을 실험하며 만들어가는 생성형 AI 비주얼 컬렉션.'},video:{label:'영상',n:'03',heading:'Ideas, now<br>in <em>motion.</em>',subtitle:'한 장면을 넘어, 하나의 이야기로.',desc:'기획부터 스토리보드까지. AI와 함께 탐색하는 움직이는 콘텐츠.'},final:{label:'Final project',n:'04',heading:'A small idea.<br>A new <em>perspective.</em>',subtitle:'배움의 조각을 하나의 프로젝트로.',desc:'리서치, 스토리텔링, 비주얼 실험을 연결한 최종 프로젝트 기록.'}};
const image=(name,alt)=>`<img src="assets/${name}.png" alt="${alt}" decoding="async">`;
const label=(a,b)=>`<div class="section-label"><span>${a}</span><span>${b}</span></div>`;
const article=`${label('01 / SELECTED ARTICLE','선택한 이야기')}<section class="feature" aria-label="대표 기사"><div class="feature-visual">${image('still-life','크림색 조형물과 반투명 유리 구로 표현한 AI 창작의 가능성')}<span class="image-note">THE ART OF A NEW PERSPECTIVE</span></div><div class="feature-copy"><div class="tags"><span class="tag">AI 인사이트</span><span>샘플 기사 · 5분 읽기</span></div><h2>AI는 우리의 창의성을<br>어디까지 넓혀줄 수 있을까?</h2><p>좋은 결과를 만드는 것은 도구일까, 질문일까.<br>생성형 AI와 함께한 첫 실습에서 발견한<br>창작의 가능성과 사람의 역할을 기록했다.</p><div class="meta"><span>2026.09.10</span><span>한국경제 AI 교육</span></div><button class="text-link" data-article="0">기사 읽기 <span>↗</span></button></div></section>${label('MORE STORIES','생각을 쌓아가는 기록')}<section class="article-list" aria-label="기사 목록">${[['좋은 프롬프트는 좋은 질문에서 시작된다','프롬프트 실습 · 질문 설계와 결과 비교','2026.09.08'],['데이터에서 이야기를 발견하는 방법','데이터 스토리텔링 · 관찰에서 기사까지','2026.09.05'],['AI 시대, 팩트체크가 더 중요해지는 이유','미디어 리터러시 · 출처 확인과 검증','2026.09.03']].map((x,i)=>`<button class="article-row" data-article="${i+1}"><span class="row-number">0${i+2}</span><span><span class="row-title" style="display:block">${x[0]}</span><span class="row-sub">${x[1]}</span></span><span class="row-date">${x[2]}</span><span class="arrow">↗</span></button>`).join('')}</section>`;
const gallery=`${label('02 / VISUAL EXPLORATIONS','이미지를 선택해 자세히 보기')}<section class="gallery" aria-label="AI 이미지 갤러리">${[['still-life','Soft Geometry','빛과 형태의 균형','크림색 종이 조형물과 장밋빛 유리 구'],['architecture','Quiet Futures','미래 공간의 고요함','부드러운 빛이 비치는 미래적 아치형 복도'],['fabric','Between Air & Form','질감으로 그리는 움직임','아이보리 구 위로 흐르는 연분홍 천']].map((x,i)=>`<button class="art-card" data-art="${i}"><div class="art-frame">${image(x[0],x[3])}</div><div class="art-caption"><h2>${x[1]}</h2><span class="arrow">↗</span></div><p>0${i+1} &nbsp; / &nbsp; ${x[2]} · AI 생성</p></button>`).join('')}</section><section class="gallery-foot"><h2>From a prompt,<br>to a possibility.</h2><p>하나의 단어를 바꾸면 빛의 방향도, 공간의 분위기도 달라집니다. 같은 주제를 다른 시선으로 바라보며 프롬프트와 결과 사이의 작은 차이를 기록합니다.</p></section>`;
const video=`${label('03 / MOTION STUDIES','영상 기획 · 샘플 모션')}<section class="cinema"><div class="screen">${image('fabric','연분홍 패브릭과 구를 활용한 모션 스터디 표지')}<button class="play" data-film="0" aria-label="The Shape of Air 모션 미리보기"><span>▶</span></button><span class="screen-label">01 — MOTION PREVIEW</span></div><div class="cinema-copy"><span class="eyebrow">FEATURED STUDY / 01</span><h2>The Shape<br>of Air</h2><h3>보이지 않는 움직임을 담다</h3><p>천의 흐름과 빛의 변화를 소재로 한 짧은 브랜드 필름 기획. 한 장의 이미지에서 영상의 리듬을 찾아갑니다.</p><div class="meta"><span>이미지 기반 모션 샘플</span><span>기획 · 연출</span></div></div></section>${label('ON THE STORYBOARD','다음 장면을 위한 실험')}<section class="video-grid">${[['architecture','Quiet City, 2030','고요한 미래 도시 · 공간 스토리보드'],['still-life','A Different Perspective','다르게 바라보기 · 제품 필름 기획']].map((x,i)=>`<button class="video-card" data-film="${i+1}"><div class="video-thumb">${image(x[0],x[1]+' 영상 기획 표지')}<span>▶</span></div><div><span class="eyebrow">STUDY / 0${i+2}</span><h3>${x[1]}</h3><p>${x[2]}</p></div></button>`).join('')}</section>`;
const final=`${label('04 / FINAL PROJECT','프로젝트 예시 · Concept study')}<section class="project-hero">${image('architecture','아치와 자연광이 이어지는 미래 공간')}<div class="project-overlay"><span class="eyebrow">AI × EDITORIAL × VISUAL</span><h2>Tomorrow,<br>in a different light.</h2><p>AI로 그려보는, 더 나은 일상의 풍경</p></div></section><dl class="project-facts"><div><dt>PROJECT</dt><dd>내일의 일상, 새로운 시선</dd></div><div><dt>ROLE</dt><dd>기획 · 리서치 · 콘텐츠 제작</dd></div><div><dt>FORMAT</dt><dd>기사 + 이미지 + 영상 기획</dd></div><div><dt>STATUS</dt><dd>프로젝트 예시</dd></div></dl><section class="case-section"><h2>01 — The question</h2><div><h3>기술이 바꾸는 일상을 어떻게 이야기할까?</h3><p>거대한 기술의 변화보다, 우리가 매일 마주하는 작은 장면에 주목했습니다. 일하는 공간, 배우는 방식, 창작하는 과정을 살펴보고 AI가 더하는 가능성을 하나의 에디토리얼 프로젝트로 엮었습니다.</p></div></section><section class="case-section"><h2>02 — The process</h2><div><h3>관찰하고, 실험하고, 연결하기</h3><div class="process"><article><span>01</span><h4>Research</h4><p>일상 속 변화 관찰<br>주제 선정과 자료 검증</p></article><article><span>02</span><h4>Create</h4><p>기사 초안과 비주얼 제작<br>프롬프트 실험과 수정</p></article><article><span>03</span><h4>Connect</h4><p>콘텐츠를 하나의 이야기로<br>구성하고 결과 돌아보기</p></article></div></div></section><section class="case-section"><h2>03 — Reflection</h2><div><h3>도구보다 먼저, 전달하고 싶은 이야기.</h3><p>이번 프로젝트의 핵심은 AI 결과물을 많이 만드는 것이 아니라, 목적에 맞는 결과를 고르는 기준을 세우는 데 있습니다. 사실은 검증하고, 이미지는 의도를 담아 선택하며, 모든 콘텐츠가 같은 질문에 답하도록 구성했습니다.</p></div></section><section class="project-end"><div><h3>The pieces behind the project.</h3><p>프로젝트를 구성한 개별 작업 살펴보기</p></div><a class="text-link" href="article.html">작업 아카이브 <span>↗</span></a></section>`;
const content={article,image:gallery,video,final};
for(const [key,p] of Object.entries(pages)){
 const html=`<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="한국경제 AI 교육에서 만든 ${p.label} 작업을 모아둔 개인 포트폴리오입니다."><meta name="theme-color" content="#f5f1ea"><title>${p.label} — AI Atelier</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><script src="app.js" defer></script></head><body data-page="${key}"><a class="skip" href="#main">본문 바로가기</a><div class="wrap"><header class="header"><a class="brand" href="article.html" aria-label="AI Atelier 홈"><span class="brand-mark">a.</span><span class="brand-name">AI Atelier<small>LEARNING ARCHIVE</small></span></a><nav class="nav" aria-label="주 메뉴">${Object.entries(pages).map(([k,v])=>`<a href="${k}.html"${k===key?' aria-current="page"':''}>${v.label}</a>`).join('')}</nav><button class="add" id="add-material">내 자료 미리보기<span>+</span></button></header><main id="main"><section class="page-intro"><div class="intro-top"><span class="eyebrow">HANKYUNG AI EDUCATION · PORTFOLIO</span><span class="number">${p.n} / 04</span></div><div class="intro-bottom"><h1>${p.heading}</h1><p class="intro-copy"><strong>${p.subtitle}</strong>${p.desc}</p></div></section>${content[key]}<section class="local-section" id="local-materials" aria-label="내 자료 미리보기"></section><p class="sample-note">현재 게시된 글과 프로젝트는 예시이며, 이미지는 AI로 제작했습니다.</p></main><footer class="footer"><div><strong>AI Atelier</strong><p>배우고, 실험하고, 나의 것으로.</p></div><div class="footer-right"><span>한국경제 AI 교육 · 개인 학습 포트폴리오</span><p>© 2026 AI Atelier. A work in progress.</p></div></footer></div><dialog id="viewer" aria-label="자료 상세보기"><div class="dialog-head"><span id="dialog-label">ARCHIVE / DETAIL</span><button class="close" aria-label="닫기">×</button></div><div class="dialog-body" id="dialog-body"></div></dialog></body></html>`;
 writeFileSync(`dist/${key}.html`,html);
 if(key==='article')writeFileSync('dist/index.html',html);
}
